name: Build

on:
  push:
    branches-ignore:
      - main

permissions:
  contents: read

concurrency:
  group: "${{ github.workflow }} @ ${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: npm
          check-latest: true
          node-version: 18
      - name: Clean install
        run: npm clean-install
        shell: bash
        env:
          HUSKY: "0"
      - name: Test package
        env:
          POWERTOOLS_DEV: true
        run: npm test
